npmPublishAccess: public

packageExtensions:
    '@types/markdown-it@*':
        dependencies:
            '@types/punycode': '*'
            punycode: '*'
    '@traptitech/markdown-it-katex@*':
        dependencies:
            '@types/markdown-it': '*'
            '@types/katex': '*'

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.4.1.cjs
