name: check

on:
    pull_request:
        branches: main

env:
    CI: true
    PNPM_CACHE_FOLDER: .pnpm-store
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: setup node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 15.x

            - name: install playwright
              run: |
                  npx playwright install-deps

            - name: install pnpm
              run: npm i pnpm@latest -g
            - name: load cache
              uses: actions/cache@v2
              with:
                  path: |
                      ./.pnpm-store
                  key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}
            - name: setup pnpm config
              run: pnpm config set store-dir $PNPM_CACHE_FOLDER
            - name: install dependencies
              run: pnpm install
            - name: build packs
              run: pnpm build:packs

            - name: run test
              run: |
                  pnpm test

            - name: run cypress
              uses: cypress-io/github-action@v2
              with:
                  start: pnpm start --filter=@milkdown/integration-test
                  wait-on: 'http://localhost:7000'
                  project: ./integration-test
                  browser: chrome
