name: gh-pages

on:
    workflow_run:
        workflows: test
        branches: main
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 15.x
              uses: actions/setup-node@v2
              with:
                  node-version: 15.x

            - name: install pnpm
              run: npm i pnpm@latest -g

            - name: cache .pnpm-store
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.pnpm-store
                      ./.pnpm-store
                  key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}

            - name: build milkdown
              run: |
                  pnpm install
                  pnpm build:doc
            - name: deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs
