name: gh-pages

on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 15.x
              uses: actions/setup-node@v2
              with:
                  node-version: 15.x

            - name: Build milkdown
              run: |
                  npm i -g pnpm
                  pnpm install
                  pnpm run build
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs
