name: integration

on:
    workflow_run:
        workflows: gh-pages
        branches: main
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 15.x
              uses: actions/setup-node@v2
              with:
                  node-version: 15.x

            - name: build milkdown
              run: |
                  npm i -g pnpm
                  npx playwright install-deps
                  pnpm install
            - name: run test
              run: |
                  pnpm pw
