# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build gh-pages

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 15.x
              uses: actions/setup-node@v2
              with:
                  node-version: 15.x
            - run: yarn
            - run: yarn workspace @milkdown/core build
            - run: yarn workspace @milkdown/preset-commonmark build
            - run: yarn workspace @milkdown/plugin-prism build
            - run: yarn workspace @milkdown/theme-nord build
            - run: yarn workspace @milkdown/gh-pages build
            - name: Deploy to GitHub Pages
              if: success()
              uses: crazy-max/ghaction-github-pages@v2
              with:
                  target_branch: gh-pages
                  build_dir: docs
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
