name: release

on:
    workflow_run:
        workflows: test
        branches: main
        types:
            - completed

env:
    CI: true
    PNPM_CACHE_FOLDER: .pnpm-store
jobs:
    release:
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - name: checkout code repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: setup node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: install pnpm
              # pnpm has bugs in @6.7, lock to wait the fix
              run: npm i pnpm@6.4 -g
            - name: creating .npmrc
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
            - name: setup pnpm config
              run: pnpm config set store-dir $PNPM_CACHE_FOLDER
            - name: install dependencies
              run: pnpm install
            - name: create versions or publish to npm registry
              uses: changesets/action@master
              with:
                  publish: pnpm release
                  commit: 'ci(changeset): prepare release'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
