name: release

on:
    push:
        branches:
            - main
env:
    CI: true
    PNPM_CACHE_FOLDER: .pnpm-store
jobs:
    release:
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - name: checkout code repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: setup node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: install pnpm
              run: npm i pnpm@latest -g
            - name: setup pnpm config
              run: pnpm config set store-dir $PNPM_CACHE_FOLDER
            - name: install dependencies
              run: pnpm install
            - name: build
              run: pnpm build
            - name: creating .npmrc
              run: |
                  cat << EOF > "$HOME/.npmrc"
                  //npm.pkg.github.com/:_authToken=$NPM_TOKEN
                  EOF
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: create versions
              uses: changesets/action@master
              with:
                  publish: pnpm publish -r --access public
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
