name: release

on:
    push:
        branches:
            - main
env:
    CI: true
    PNPM_CACHE_FOLDER: .pnpm-store
jobs:
    release:
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - name: checkout code repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: setup node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: creating .npmrc
              run: |
                  cat << EOF > "./.npmrc"
                  //registry.npmjs.org/:_authToken=\${NPM_TOKEN}
                  EOF
            - name: install pnpm
              run: npm i pnpm@latest -g
            - name: setup pnpm config
              run: pnpm config set store-dir $PNPM_CACHE_FOLDER
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: install dependencies
              run: pnpm install
            - name: build
              run: pnpm run build -r --filter "packages/"
            - name: create versions or publish to npm registry
              uses: changesets/action@master
              with:
                  publish: pnpm publish -r --access public
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: setup node.js for github packages
              uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: 'https://npm.pkg.github.com'
            - name: echo .npmrc
              run: cat .npmrc
            - name: publish to github packages
              run: pnpm publish -r
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
